### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by pmarks-net** [FrenkelS/Doom8088#12]
Please take a screenshot of Doom8088 (e.g. using an emulator or camera) and add it to README.md.  This would greatly increase the number of people who can see what you've accomplished:

https://stackoverflow.com/questions/10189356/how-to-add-screenshot-to-readmes-in-github-repository

**Comment by FrenkelS** [comment]
I've added a screenshot and a link to a video of Doom8088 running on a real 286.
