### ISSUE TITLE
"Can't open VIEWANGX.LMP" under DOS 3.31 on FAT16 hard drive

### ISSUE THREAD

**Issue by ninakali** [FrenkelS/Doom8088#13]
Hi! I'm trying to run Doom8088 in pcem with emulated 286+287 running AMI BIOS, MS-DOS 3.31 and FAT16 hard drive (roughly similar to an actual machine I have), and it refuses to start, complaining that it can't open the file "VIEWANGX.LMP" after allocating 317984 bytes of RAM. The file is present on the disk, of course.

**Comment by FrenkelS** [comment]
I had the same problem, but it went away when I put `FILES=30` in my `config.sys`. Maybe a value smaller than 30 also works.

**Comment by ninakali** [comment]
I added FILES=30 to config.sys, and now it boots and kind of works. I imagine there's lots of room for optimisation :) But it does look very pretty on a VGA card.

**Comment by FrenkelS** [comment]
I've added it to README.md.
