### ISSUE TITLE
Please release binaries. 

### ISSUE THREAD

**Issue by mindbleach** [FrenkelS/Doom8088#34]
I've spent three days getting this to compile. `wmake` doesn't match its documentation, `gcc-ia16` has no real documentation, and wcc386 will not obey case-sensitive output names. I still can't tell if it worked, because it dies on `W_GetNumForName: STGANUM0 not found`, and I have no way to tell if that's the program or the processed WAD being wrong. 

It would be extremely helpful if you included your EXEs. 

It would also be nice to include FreeDoom or Miniwad, processed appropriately. Even if only one or two levels work. 

Having tilted at this particular windmill several years ago, I would very much like to help optimize this project's renderer. But I am at my limit for guessing games with ancient compilers and makefile witchcraft.

**Comment by FrenkelS** [comment]
The zip files on the [Releases page](https://github.com/FrenkelS/Doom8088/releases) contains executables and a processed Doom1.wad.

**Comment by mindbleach** [comment]
Welp. 

On the plus side for my ego, it was just GbaWadUtil being dorked-up somehow. 

I have a minor flat-span performance boost from skipping visplanes entirely, but I'm not pushing it yet because it doesn't match the new floor / ceiling colors.
